matrix:
	  include:    
	    - language: c  
	      sudo: false # only for faster builds  
	      compiler:
	        - clang
	        - gcc
	      script:  
	        - gcc -o heena.c 
	        - ./heena
	        - gcc -o Asses1.c
	        - ./Asses1
	        - gcc -o CODE.c
	        - ./CODE
          - gcc -o palindrome.c
          - ./palindrome
        
