matrix:
  include:
    - language: c
      sudo: false # only for faster builds
      compiler:
        - clang
        - gcc
      script:
        - gcc -o test1 CODE.c
        - gcc -o test2 heena.c
        - gcc -o test3 Asses1.c
        - gcc -o test4 palindrome.c
        - ./test1
        - ./test2
        - ./test3
        - ./test4

        
        
