matrix:
  include:
    - language: c
      sudo: false # only for faster builds
      compiler:
        - clang
        - gcc
      script:
        - gcc -o test CODE.c
        - gcc -o test heena.c
        - gcc -o test Asses1.c
        - gcc -o test palindrome.c
        - ./test
